
version: 2

sources:
    - name: raw
      schema: raw_data0826_circle
      description: "Source tables"
      tables:
        - name: parcel
          identifier: raw_cc_parcel
          description: parcel data
          columns:
            - name: parcel_id
              description: unique id of the parcel
              tests:
                - unique
                - not_null
                - dbt_utils.not_constant
        - name: parcel_product
          identifier: raw_cc_parcel_product
          description: each product included in a parcel
          columns:
            - name: parcel_id
              description: id of the parcel
              tests:
                - not_null
            - name: model_mame
              description: model included in a parcel
              tests:
                - not_null
          tests:
            - unique:
                column_name: 'parcel_id || "-" || model_mame'
            
                        